version: "3.8"

services:
  mysql-test:
    build:
      context: ./mysql
      dockerfile: Dockerfile.test
      args:
        MYSQL_VERSION: 8.4
        TIMEZONE: Asia/Shanghai
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: test123
      TZ: Asia/Shanghai
    ports:
      - "33061:3306"
    volumes:
      - ./data/mysql-test:/var/lib/mysql
    restart: unless-stopped
