# Homepage 仪表板配置
# 文件: traefik/config/dynamic/homepage.yml

http:
  services:
    homepage:
      loadBalancer:
        servers:
          - url: "http://homepage:3000"
        passHostHeader: true

  routers:
    homepage:
      entryPoints:
        - websecure
      rule: 'Host(`home.{{ env "DOMAIN" }}`)'
      service: homepage
      middlewares:
        - web-chain@file
      tls:
        certResolver: default
      priority: 60
