# MinIO 对象存储配置
# 文件: traefik/config/minio.yml

http:
  services:
    minio:
      loadBalancer:
        servers:
          - url: "http://minio:9001"
        passHostHeader: true

  routers:
    minio:
      entryPoints:
        - "websecure"
      priority: 20
      service: "minio"
      rule: 'Host(`minio.{{ env "DOMAIN" }}`)'
      tls: {}
