# Portainer 容器管理配置
# 文件: traefik/config/portainer.yml
http:
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
        passHostHeader: true

  routers:
    portainer:
      entryPoints:
        - "websecure"
      priority: 20
      service: "portainer"
      rule: 'Host(`portainer.{{ env "DOMAIN" }}`)'
      tls: {}
