# 容器注册表配置
# 文件: traefik/config/registry.yml

http:
  services:
    registry:
      loadBalancer:
        servers:
          - url: "http://registry:5000"
        passHostHeader: true

  routers:
    registry:
      entryPoints:
        - "websecure"
      priority: 30
      service: "registry"
      rule: 'Host(`registry.{{ env "DOMAIN" }}`)'
      tls: {}
