tunnel: b35440ae-e7b3-41b7-874e-c64b878c4500  # 替换为步骤2生成的隧道ID
# 配置路由规则：将域名映射到内网服务（如 Caddy 监听的 localhost:80）
credentials-file: /etc/cloudflared/cert.pem
ingress:
  - hostname: fpm.jso.lol  # 你的 Cloudflare 域名
    service: http://caddy:80   # 内网服务地址（Caddy 容器名+端口，需同一网络）

#  - hostname: octane.jso.lol
#    service: http_status:200  # <--- 临时修改为 200 OK
#    service: http://php-franken:8001
#    service: http:/localhost:8801

  - service: http_status:404  # 兜底规则无匹配时返回404