name: Build PostgreSQL with PostGIS Multi-arch Images

# 手动触发构建PostgreSQL+PostGIS多平台镜像
on:
  workflow_dispatch:
    inputs:
      postgres_version:
        description: "PostgresSQL版本 (例如: 17.6)"
        required: true
        default: "17.6"
      tag:
        description: "镜像标签 (例如: latest)"
        required: true
        default: "latest"

jobs:
  # 构建pgsql多平台镜像并推送
  build-pgsql-multiarch:
    runs-on: ubuntu-latest
    env:
      POSTGRES_VERSION: ${{ github.event.inputs.postgres_version }}
      TAG: ${{ github.event.inputs.tag }}
      REGISTRY_DOCKERHUB: docker.io/jiaoio
      REGISTRY_REDHAT: quay.io/jiaoio
      REGISTRY_TENCENT: ccr.ccs.tencentyun.com/jiaoio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to RedHat Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REDHAT_REGISTRY_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_TOKEN }}

      - name: Login to Tencent Cloud Registry
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}

      - name: Build pgsql multi-arch image
        run: |
          cd pgsql && docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg CHANGE_SOURCE=false \
            --build-arg POSTGRES_VERSION=$POSTGRES_VERSION-alpine \
            --tag $REGISTRY_DOCKERHUB/pgsql:$POSTGRES_VERSION-$TAG \
            --tag $REGISTRY_DOCKERHUB/pgsql:$POSTGRES_VERSION-postgis-$TAG \
            --tag $REGISTRY_DOCKERHUB/pgsql:latest \
            --tag $REGISTRY_REDHAT/pgsql:$POSTGRES_VERSION-$TAG \
            --tag $REGISTRY_REDHAT/pgsql:$POSTGRES_VERSION-postgis-$TAG \
            --tag $REGISTRY_REDHAT/pgsql:latest \
            --tag $REGISTRY_TENCENT/pgsql:$POSTGRES_VERSION-$TAG \
            --tag $REGISTRY_TENCENT/pgsql:$POSTGRES_VERSION-postgis-$TAG \
            --tag $REGISTRY_TENCENT/pgsql:latest \
            --push \
            .
